// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -package cron -source event.go -destination mockevent.go
//

// Package cron is a generated GoMock package.
package cron

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// GetDayOfMonth mocks base method.
func (m *MockEvent) GetDayOfMonth() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDayOfMonth")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetDayOfMonth indicates an expected call of GetDayOfMonth.
func (mr *MockEventMockRecorder) GetDayOfMonth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDayOfMonth", reflect.TypeOf((*MockEvent)(nil).GetDayOfMonth))
}

// GetDayOfWeek mocks base method.
func (m *MockEvent) GetDayOfWeek() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDayOfWeek")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetDayOfWeek indicates an expected call of GetDayOfWeek.
func (mr *MockEventMockRecorder) GetDayOfWeek() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDayOfWeek", reflect.TypeOf((*MockEvent)(nil).GetDayOfWeek))
}

// GetHour mocks base method.
func (m *MockEvent) GetHour() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHour")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetHour indicates an expected call of GetHour.
func (mr *MockEventMockRecorder) GetHour() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHour", reflect.TypeOf((*MockEvent)(nil).GetHour))
}

// GetID mocks base method.
func (m *MockEvent) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockEventMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockEvent)(nil).GetID))
}

// GetMinute mocks base method.
func (m *MockEvent) GetMinute() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinute")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetMinute indicates an expected call of GetMinute.
func (mr *MockEventMockRecorder) GetMinute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinute", reflect.TypeOf((*MockEvent)(nil).GetMinute))
}

// GetMonth mocks base method.
func (m *MockEvent) GetMonth() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonth")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetMonth indicates an expected call of GetMonth.
func (mr *MockEventMockRecorder) GetMonth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonth", reflect.TypeOf((*MockEvent)(nil).GetMonth))
}
