// Code generated by MockGen. DO NOT EDIT.
// Source: cron.go
//
// Generated by this command:
//
//	mockgen -package cron -source cron.go -destination mockcron.go
//

// Package cron is a generated GoMock package.
package cron

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCron is a mock of Cron interface.
type MockCron struct {
	ctrl     *gomock.Controller
	recorder *MockCronMockRecorder
	isgomock struct{}
}

// MockCronMockRecorder is the mock recorder for MockCron.
type MockCronMockRecorder struct {
	mock *MockCron
}

// NewMockCron creates a new mock instance.
func NewMockCron(ctrl *gomock.Controller) *MockCron {
	mock := &MockCron{ctrl: ctrl}
	mock.recorder = &MockCronMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCron) EXPECT() *MockCronMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockCron) Schedule(event Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", event)
}

// Schedule indicates an expected call of Schedule.
func (mr *MockCronMockRecorder) Schedule(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockCron)(nil).Schedule), event)
}

// Start mocks base method.
func (m *MockCron) Start() (<-chan *Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(<-chan *Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockCronMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCron)(nil).Start))
}

// Stop mocks base method.
func (m *MockCron) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCronMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCron)(nil).Stop))
}

// Unschedule mocks base method.
func (m *MockCron) Unschedule(event string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unschedule", event)
}

// Unschedule indicates an expected call of Unschedule.
func (mr *MockCronMockRecorder) Unschedule(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unschedule", reflect.TypeOf((*MockCron)(nil).Unschedule), event)
}
