// Code generated by MockGen. DO NOT EDIT.
// Source: bulkcreate.go
//
// Generated by this command:
//
//	mockgen -source=bulkcreate.go -package mocks -destination mocks/bulkcreate.mock.gen.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	sql "database/sql"
	reflect "reflect"

	record "github.com/beaconsoftwarellc/gadget/v2/database/record"
	errors "github.com/beaconsoftwarellc/gadget/v2/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockBulkCreate is a mock of BulkCreate interface.
type MockBulkCreate[T record.Record] struct {
	ctrl     *gomock.Controller
	recorder *MockBulkCreateMockRecorder[T]
}

// MockBulkCreateMockRecorder is the mock recorder for MockBulkCreate.
type MockBulkCreateMockRecorder[T record.Record] struct {
	mock *MockBulkCreate[T]
}

// NewMockBulkCreate creates a new mock instance.
func NewMockBulkCreate[T record.Record](ctrl *gomock.Controller) *MockBulkCreate[T] {
	mock := &MockBulkCreate[T]{ctrl: ctrl}
	mock.recorder = &MockBulkCreateMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkCreate[T]) EXPECT() *MockBulkCreateMockRecorder[T] {
	return m.recorder
}

// Commit mocks base method.
func (m *MockBulkCreate[T]) Commit() (sql.Result, errors.TracerError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(errors.TracerError)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockBulkCreateMockRecorder[T]) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockBulkCreate[T])(nil).Commit))
}

// Create mocks base method.
func (m *MockBulkCreate[T]) Create(objs ...T) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range objs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Create", varargs...)
}

// Create indicates an expected call of Create.
func (mr *MockBulkCreateMockRecorder[T]) Create(objs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBulkCreate[T])(nil).Create), objs...)
}

// Reset mocks base method.
func (m *MockBulkCreate[T]) Reset() errors.TracerError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset")
	ret0, _ := ret[0].(errors.TracerError)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockBulkCreateMockRecorder[T]) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockBulkCreate[T])(nil).Reset))
}

// Rollback mocks base method.
func (m *MockBulkCreate[T]) Rollback() errors.TracerError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(errors.TracerError)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockBulkCreateMockRecorder[T]) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockBulkCreate[T])(nil).Rollback))
}
